[project]
name = "llm_coding"
version = "0.1.0"
description = "Experiments with LLMs to plan, code, and package a software."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv",
    "ruff>=0.9.6",
    "openai",
    "mdformat",
    "black[jupyter]",
    "isort",
]
